services:
  - type: web_service
    name: visitor-registration-via-voice
    id: srv-d83gj9lckfvc73bkr7fg
    env: node
    branch: main
    buildCommand: "cd backend && npm ci"
    startCommand: "cd backend && npm start"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CRM_ENDPOINT
        sync: false
      - key: PORT
        value: "4000"
    plan: starter

  - type: static_site
    name: visitor-registration-frontend
    env: static
    branch: main
    buildCommand: "cd frontend && npm ci && npm run build"
    publishPath: "frontend/dist"
    envVars:
      - key: VITE_API_BASE
        sync: false
    plan: starter
